### ISSUE TITLE
What is an ID TOKEN?

### ISSUE THREAD

**Issue by andersonmech** [alpkeskin/Chegg-Discord-Bot#2]
I understand what USER AGENT and BOT TOKEN are, but I'm not sure what an ID TOKEN is. I see that it is used in the header in assignation to 'cookie', so I imagine that's what it's for. In either case, how do I find my ID TOKEN?

**Comment by ronzron** [comment]
Can i ask about user agent is? like where to see it?

**Comment by alpkeskin** [comment]
Hello guys, you can find ID token and User Agent from **Cookies** 👍  If you have more questions you can add me on discord(dada#3705).  Also don't forget to _star_ :)
