### ISSUE TITLE
The request is being blocked....by the site

### ISSUE THREAD

**Issue by RohitMaddiboina** [alpkeskin/Chegg-Discord-Bot#3]
<div class="content-wrapper">
<div class="content">
<div id="px-captcha">
</div>
<p>
                Access to this page has been denied because we believe you are using automation tools to browse the
                website.
            </p>
<p>
                This may happen as a result of the following:
            </p>
<ul>
<li>
                    Javascript is disabled or blocked by an extension (ad blockers for example)
                </li>
<li>
                    Your browser does not support cookies
                </li>
</ul>
<p>
                Please make sure that Javascript and cookies are enabled on your browser and that you are not blocking
                them from loading.
            </p>
<p>
                Reference ID: ###############################
            </p>
</div>
</div>
<div class="page-footer-wrapper">
<div class="page-footer">
<p>
                Powered by
                <a href="https://www.perimeterx.com/whywasiblocked">PerimeterX</a>
                , Inc.
            </p>
</div>
</div>
</section>

<script>
    window._pxAppId = 'PXzYvFOXaC';
    window._pxJsClientSrc = '/zYvFOXaC/init.js';
    window._pxFirstPartyEnabled = true;
    window._pxVid = '';
    window._pxUuid = '4dde0740-4424-11eb-aed8-3f4aa5196f7f';
    window._pxHostUrl = '/zYvFOXaC/xhr';
</script>
<script>
    var s = document.createElement('script');
    s.src = '/zYvFOXaC/captcha/captcha.js?a=c&u=4dde0740-4424-11eb-aed8-3f4aa5196f7f&v=&m=0';
    var p = document.getElementsByTagName('head')[0];
    p.insertBefore(s, null);
    if (true) {
        s.onerror = function () {
            s = document.createElement('script');
            var suffixIndex = '/zYvFOXaC/captcha/captcha.js?a=c&u=4dde0740-4424-11eb-aed8-3f4aa5196f7f&v=&m=0'.indexOf('captcha.js');
            var temperedBlockScript = '/zYvFOXaC/captcha/captcha.js?a=c&u=4dde0740-4424-11eb-aed8-3f4aa5196f7f&v=&m=0'.substring(suffixIndex);
            s.src = '//captcha.px-cdn.net/PXzYvFOXaC/' + temperedBlockScript;
            p.parentNode.insertBefore(s, p);
        };
    }
</script>

</body>
</html>

**Comment by alpkeskin** [comment]
yeap this code is banned and also I will not share the unbanned version. stay safe 💯
